# Generated by Django 4.0.2 on 2022-04-30 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import music.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='album_images/', verbose_name='Album Image')),
                ('name_of_album', models.CharField(max_length=250, verbose_name='Album name')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_genre', models.CharField(max_length=100, verbose_name='Genre name')),
                ('description', models.TextField(verbose_name='Description of genre')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_file', models.FileField(upload_to='musics/', validators=[music.validators.validate_is_audio], verbose_name='Music File')),
                ('cover_image', models.ImageField(upload_to='music_images/')),
                ('name_of_song', models.CharField(max_length=250, verbose_name='Music name')),
                ('time_length', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('release_date', models.DateField(auto_now_add=True, verbose_name='Release date')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('author_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='accounts.artistprofile', verbose_name='Select a author')),
                ('genre', models.ManyToManyField(to='music.Genre', verbose_name='Genre of music')),
            ],
            options={
                'verbose_name': 'Music',
                'verbose_name_plural': 'Musics',
            },
        ),
        migrations.CreateModel(
            name='FavouriteMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_music', models.BooleanField(default=False, verbose_name='Are you like it?')),
                ('music_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.music')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favourite Music',
                'verbose_name_plural': 'Favourite Musics',
            },
        ),
        migrations.CreateModel(
            name='FavouriteAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_album', models.BooleanField(default=False, verbose_name='Are you like it?')),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.artistprofile')),
            ],
            options={
                'verbose_name': 'Favourite Album',
                'verbose_name_plural': 'Favourite Albums',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='add_music',
            field=models.ManyToManyField(to='music.Music', verbose_name='Add music'),
        ),
        migrations.AddField(
            model_name='album',
            name='author_of_album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_albums', to='accounts.artistprofile', verbose_name='Author of album'),
        ),
    ]
