# Generated by Django 4.0.2 on 2022-05-08 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0002_music_text_of_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouritemusic',
            name='music_id',
        ),
        migrations.RemoveField(
            model_name='favouritemusic',
            name='user_id',
        ),
        migrations.AddField(
            model_name='album',
            name='like_album',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Do you like this album?'),
        ),
        migrations.AddField(
            model_name='music',
            name='like_music',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Do you like this music?'),
        ),
        migrations.DeleteModel(
            name='FavouriteAlbum',
        ),
        migrations.DeleteModel(
            name='FavouriteMusic',
        ),
    ]
